### ISSUE TITLE
Error installing Moodle27 branch in Moodle 2.7.9+ (Build: 20150813)

### ISSUE THREAD

**Issue by hello-josh** [frumbert/moodle-course_meta#3]
I copied the folders into my moodle install's `local` folder

```
local$ ls -la
total 24
drwxr-xr-x   5 Josh  staff    170 Aug 27 11:55 .
drwxr-xr-x  70 Josh  staff   2380 Aug 27 11:59 ..
drwxr-xr-x  10 Josh  staff    340 Aug 27 11:55 course_meta
drwxr-xr-x   4 Josh  staff    136 Aug 27 11:55 customscripts
```

But when I hit the install page I get the following error

![image](https://cloud.githubusercontent.com/assets/638073/9525680/4d1f4d6e-4cb3-11e5-8f3c-5e7d753e482f.png)

**Comment by hello-josh** [comment]
This is a fresh install of Moodle and your plugin. No other modifications made ... yet.

**Comment by frumbert** [comment]
Hmm, try deleting the `course-meta/db/access.php` file, looks like that's in there by mistake in that branch.

**Comment by hello-josh** [comment]
That works!
