### ISSUE TITLE
Getting no option to create custom fields

### ISSUE THREAD

**Issue by walkwelsubmission** [frumbert/moodle-course_meta#6]
Hello,

I have installed this plugin but I am not seeing any option for custom fields creation.

I can see an option which says "manage custom fields" but choosing that option takes me to a screen which is also not having any option to have custom field created.

Please find attached screenshots for better understanding.

My moodle version is 3.1

Regards
![customfiedls2](https://cloud.githubusercontent.com/assets/20394133/16723180/19ebff3a-4769-11e6-8b3b-eebb7687be7a.png)
![customfiedls1](https://cloud.githubusercontent.com/assets/20394133/16723188/1e820b66-4769-11e6-9bea-74f8613e1ac6.png)

**Comment by frumbert** [comment]
Did you then use the "Create a new profile field" drop down and choose a field type? This works in the same way as custom profile fields for users ...

If that doesn't work, can you list the contents of the `/user/profile/field` folder and the `/local/course_meta/profile/field` folders?
